apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: fazil2664/app:69   # 👈 Jenkins will update this
          imagePullPolicy: Always       # 👈 IMPORTANT
          ports:
            - containerPort: 8080
          resources:                   # 👈 best practice
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
